### PR TITLE
impr: New PR template for standardization

### PR DESCRIPTION
**Pull request by wildtron**
## Ticket references

- [](https://freedom.myjetbrains.com/youtrack/issue/)

## Checklist

- [ ] added unittest and works
- [ ] changes has been reviewed and approved
- [ ] requires manual testing
- [ ] documentation has been updated

```
Above is how the content below will look like

<!--
    Title your pull request with the following:
        fix: <short description>
            (FIX) This are bugs, issues or broken code that works not they way 
            they were intended to be.
            
        impr: <short description>
            (IMPROVEMENT) This are improvements introduced to the code because 
            of better implementation, readability or performance. The code 
            becomes less complex and rigid and easier to read and understand.

        feat: <short description>
            (FEATURE) This are the new code to be introduced to the codebase. 
            They may be from stories, features or tasks. As long as they are new
            functionality, they fall in this category

    Rationale for this titling sense:
        Naming the pull request with ticket title doesn't give us much context
        whenever the ticket title doesn't have context as well. The ticket
        titles are longer and they just look bad on commits when you visit the
        code commits to the primary branch. Another thing is, the tickets
        contains redundancy in the name e.g. HD-XXX Earnings > some Change.
        Including "Earnings" in ther is a bit redandunt and not really useful.

        The repository's information should not be mixed with the ticketing 
        or issuing tracking system. having the ticket reference should be enough
-->

## Ticket references
<!--

-->
- [](https://freedom.myjetbrains.com/youtrack/issue/)

## Summary of changes
<!-- 
    Describe the change and why was it introduced. Ideally this will also be
    used as the commit message when we do squash merge.

    This better be presented in paragraph form instead. Only use bullet
    form when enumerating specific parts of the change

    Include screenshots, if possible

    Rationale for the Summary of changes instead of list of changes
        The content of the list of changes are bunch of changes that are
        not correlated to each other. There are disconnect from each of the list
        and doesn't explain the purpose of the change. Looking back, reading
        the commit messages in git log is helpful if the messages contain
        a complete though and explains the purpose of the proposed changes.
        Doing lists gives the developer the ability to dissect the information 
        into an unordered list instead of having a thought or track of changes 
        grouped together in a single sentence or paragraph
-->
## Checklist
<!--
     Mark the things the things that have been followed
-->
- [ ] added unittest and works
- [ ] changes has been reviewed and approved
- [ ] requires manual testing
- [ ] documentation has been updated

<!-- 

## Testing
<!--
    Include this if we need manual testing and not unit test. If the tests does
    not reach 10 lines, add it here, else move it to a document and link it 
    to this section

-->
```

### CODE REVIEW

**Comment by aloremia-freedom** [comment]
I think it looks better without the horizontal bars

**Comment by wildtron** [comment]
@aloremia-freedom removed.

**Comment by pandafox** [comment]
Let'ts move this to gitlab or invite everyone to check, for the ticket titles, I think we'll need to introduce something else in order for this to work with CI (jenkins + youtrack)

1. the PR/commit should be automatically linked to youtrack ticket
2. CI to skip PR with title starting with [WIS] (not confirmed) https://github.com/jenkinsci/gitlab-plugin/issues/261

**Comment by wildtron** [comment]
Moved this to gitlab.

**Pull request closed without merging**
